src/Entity/Produits.php
<?php

namespace App\Entity;

use App\Repository\ProduitsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProduitsRepository::class)]
class Produits
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_produit = null;

    #[ORM\Column(type: "text")]
    private ?string $description_produit = null;

    #[ORM\Column(length: 255)]
    private ?string $image_produit = null;

    #[ORM\Column]
    private ?bool $stock_produit = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_depot_produit = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomProduit(): ?string
    {
        return $this->nom_produit;
    }

    public function setNomProduit(string $nom_produit): static
    {
        $this->nom_produit = $nom_produit;

        return $this;
    }

    public function getDescriptionProduit(): ?string
    {
        return $this->description_produit;
    }

    public function setDescriptionProduit(string $description_produit): static
    {
        $this->description_produit = $description_produit;

        return $this;
    }

    public function getImageProduit(): ?string
    {
        return $this->image_produit;
    }

    public function setImageProduit(string $image_produit): static
    {
        $this->image_produit = $image_produit;

        return $this;
    }

    public function isStockProduit(): ?bool
    {
        return $this->stock_produit;
    }

    public function setStockProduit(bool $stock_produit): static
    {
        $this->stock_produit = $stock_produit;

        return $this;
    }

    public function getDateDepotProduit(): ?\DateTimeInterface
    {
        return $this->date_depot_produit;
    }

    public function setDateDepotProduit(\DateTimeInterface $date_depot_produit): static
    {
        $this->date_depot_produit = $date_depot_produit;

        return $this;
    }
}

src/Form/ProduitsType.php
<?php

namespace App\Form;

use App\Entity\Produits;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProduitsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_produit')
            ->add('description_produit')
            ->add('image_produit')
            ->add('stock_produit')
            ->add('date_depot_produit')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Produits::class,
        ]);
    }
}

src/Controller/ProduitsController.php
<?php

namespace App\Controller;

use App\Entity\Produits;
use App\Form\ProduitsType;
use App\Repository\ProduitsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/produits')]
class ProduitsController extends AbstractController
{
    #[Route('/', name: 'app_produits_index', methods: ['GET'])]
    public function index(ProduitsRepository $produitsRepository): Response
    {
        return $this->render('produits/index.html.twig', [
            'produits' => $produitsRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_produits_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $produit = new Produits();
        $form = $this->createForm(ProduitsType::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($produit);
            $entityManager->flush();

            return $this->redirectToRoute('app_produits_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('produits/new.html.twig', [
            'produit' => $produit,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_produits_show', methods: ['GET'])]
    public function show(Produits $produit): Response
    {
        return $this->render('produits/show.html.twig', [
            'produit' => $produit,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_produits_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Produits $produit, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ProduitsType::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_produits_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('produits/edit.html.twig', [
            'produit' => $produit,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_produits_delete', methods: ['POST'])]
    public function delete(Request $request, Produits $produit, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$produit->getId(), $request->request->get('_token'))) {
            $entityManager->remove($produit);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_produits_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/produits/_delete_form.html.twig
<form method="post" action="{{ path('app_produits_delete', {'id': produit.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ produit.id) }}">
    <button class="btn">Delete</button>
</form>

templates/produits/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/produits/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Produits{% endblock %}

{% block body %}
    <h1>Edit Produits</h1>

    {{ include('produits/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_produits_index') }}">back to list</a>

    {{ include('produits/_delete_form.html.twig') }}
{% endblock %}

templates/produits/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produits index{% endblock %}

{% block body %}
    <h1>Produits index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_produit</th>
                <th>Description_produit</th>
                <th>Image_produit</th>
                <th>Stock_produit</th>
                <th>Date_depot_produit</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for produit in produits %}
            <tr>
                <td>{{ produit.id }}</td>
                <td>{{ produit.nomProduit }}</td>
                <td>{{ produit.descriptionProduit }}</td>
                <td>{{ produit.imageProduit }}</td>
                <td>{{ produit.stockProduit ? 'Yes' : 'No' }}</td>
                <td>{{ produit.dateDepotProduit ? produit.dateDepotProduit|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_produits_show', {'id': produit.id}) }}">show</a>
                    <a href="{{ path('app_produits_edit', {'id': produit.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_produits_new') }}">Create new</a>
{% endblock %}

templates/produits/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Produits{% endblock %}

{% block body %}
    <h1>Create new Produits</h1>

    {{ include('produits/_form.html.twig') }}

    <a href="{{ path('app_produits_index') }}">back to list</a>
{% endblock %}

templates/produits/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produits{% endblock %}

{% block body %}
    <h1>Produits</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ produit.id }}</td>
            </tr>
            <tr>
                <th>Nom_produit</th>
                <td>{{ produit.nomProduit }}</td>
            </tr>
            <tr>
                <th>Description_produit</th>
                <td>{{ produit.descriptionProduit }}</td>
            </tr>
            <tr>
                <th>Image_produit</th>
                <td>{{ produit.imageProduit }}</td>
            </tr>
            <tr>
                <th>Stock_produit</th>
                <td>{{ produit.stockProduit ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Date_depot_produit</th>
                <td>{{ produit.dateDepotProduit ? produit.dateDepotProduit|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_produits_index') }}">back to list</a>

    <a href="{{ path('app_produits_edit', {'id': produit.id}) }}">edit</a>

    {{ include('produits/_delete_form.html.twig') }}
{% endblock %}